apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo

metadata:
  name: build-sorted

resources:
- ../base
- ../with-lua-http-filter-unsorted


commonLabels:
  purpose: mock-microservice

