apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These labels are added to all configmaps and secrets.
generatorOptions:
  disableNameSuffixHash: true
  labels:
    wiremock-stubbing: "true"

configMapGenerator:
  - name: json-mappings
    behavior: create
    files:
      - ./mappings.json
