apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-api
  annotations:
    inject-proxy-traffic-interceptor: 'true'
    sidecar.istio.io/inject: 'true'
spec:
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
      annotations:
        sidecar.istio.io/inject: 'true'
        inject-proxy-traffic-interceptor: 'true'
        test-me: "hello-there!"
        manifestName: Employee
        jobType: Restrict
        clientId: postman
        servicePort: "9999"
        protectNullValues: "true"
        preserveStringLength: "false"
    spec:
      imagePullSecrets:
        - name: quay-puller
      volumes:
        - name: mocks-file
          configMap:
            name: json-mappings
      containers:
        - name: wiremock-server
          image: "quay.io/zgrinber/wiremock:latest"
          command: [ "bash" , "-c" ,"java -jar /var/wiremock/lib/wiremock-jre8-standalone.jar --port 9999"]
          env:
            - name: test-me
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['test-me']
          volumeMounts:
            - mountPath: /tmp/mocks
              name: mocks-file
          ports:
            - containerPort: 9999
              name: http
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh","-c", " sleep 1 ; curl -X POST http://localhost:9999/__admin/mappings/import -T /tmp/mocks/mappings.json " ]