apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: build
namespace: test
resources:
- ../base
- ./proxy-config.yaml
- ./mock-employees-api.yaml
- ./http-lua-envoy-filter.yaml
- ./service-entry.yaml
- ./virtual-service.yaml
- ./ingress-gateway.yaml

commonLabels:
  purpose: mock-microservice

