apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-distributed-tracing-
  annotations:
    olm.providedAPIs: Jaeger.v1.jaegertracing.io
  namespace: openshift-distributed-tracing
spec: {}
