apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  general:
    logging:
      logAsJSON: false
      componentLevels:
        name: debug
        level: debug
      logLevels:
        name: debug
        level: debug
  addons:
    grafana:
      enabled: true
    jaeger:
      name: jaeger
      install:
        storage:
          type: memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.3