apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: build
namespace: test
resources:
- ../base
- ./mock-employees-api.yaml
- ./ingress-gateway.yaml
- ./virtual-service.yaml
commonLabels:
  purpose: mock-microservice

