kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anyuid-scc-role
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anyuid-scc-role
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: anyuid-scc-role
  apiGroup: rbac.authorization.k8s.io
